- name: deploy to prod
  hosts: prod
  gather_facts: false

  vars:
    remote_jar: /opt/web/app.jar

  tasks:
    - name: copy jar to prod
      ansible.builtin.copy:
        src: "{{ jar_path }}"
        dest: "{{ remote_jar }}"
    - name: restarting web service
      ansible.builtin.command: sudo /usr/bin/systemctl restart web
      changed_when: true
